### ISSUE TITLE
how to set this up

### ISSUE THREAD

**Issue by suricloud** [FiorenMas/Cloudflare-Gateway-Update-DDNS-For-DNS-Locations#1]
Hi,
Can you share the steps how to run this script ?

**Comment by suricloud** [comment]
I got it how to setup.
I want to update 3 gateways ddns, how to this ?

**Comment by FiorenMas** [comment]
You can click use template create 3 repo and you can update 3 gateways...

**Comment by ShailendraMadarie** [comment]
Thanks :)

**Comment by suricloud** [comment]
Hi,

 I noticec this,
i have set 3 location gateway on cloudflare.When a ip is updated trough this script it select thar location as default on cloudflare. How to fix this.I just want 1 location to be default which i selected manually.
