### ISSUE TITLE
default locations change evytime ip gets updated

### ISSUE THREAD

**Issue by suricloud** [FiorenMas/Cloudflare-Gateway-Update-DDNS-For-DNS-Locations#2]
Hi,

I noticecd this,
i have set 3 location gateway on cloudflare.When a ip is updated trough this script it select that location as default on cloudflare. How to fix this.I just want 1 location to be default which i selected manually.

**Comment by FiorenMas** [comment]
You can edited line 19 true or false by yourself for default locations or not
