### ISSUE TITLE
Enable EDNS client subnet is removed every time the script runs

### ISSUE THREAD

**Issue by mruizdia** [FiorenMas/Cloudflare-Gateway-Update-DDNS-For-DNS-Locations#3]
Hi, 
The script works great, but just one thing, the script is not setting the option "Enable EDNS client subnet" in fact, every time the script runs it removes the option.

I couldn't find how to enable it using your script, can you help with it please?

Thanks!

<img width="626" alt="image" src="https://github.com/FiorenMas/Cloudflare-Gateway-Update-DDNS-For-DNS-Locations/assets/40149812/5a56f1a3-0dd6-45d6-be9d-195c55b52891">

**Comment by FiorenMas** [comment]
I updated just edit line 18 true or false

**Comment by mruizdia** [comment]
Hi, Thanks a lot,
It finally works, but only after I removed, he lines 18 and 20, seems it was not being taken as comments for some reason.

now, it's up and running!
thanks,
Mauro.
________________________________
